// import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google"
// import "./globals.css"
// import { Toaster } from "@/components/ui/sonner"
// import { Suspense } from "react"
// import { Analytics } from "@vercel/analytics/next"


// const geistSans = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// })

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
//   variable: "--font-geist-mono",
// })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
       
//       <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
//        <Suspense fallback={null}>{children}
//         <Toaster />
//        </Suspense>
//         <Analytics />
//       </body>
//     </html>
//   )
// }



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { Toaster } from '@/components/ui/sonner';
import { Suspense } from "react"

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Form builder Pro',
  description: 'Form buildong and data collection platform',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <Providers> */}
            <ThemeProvider attribute="class" defaultTheme="light" enableSystem = {true}>
<Suspense fallback={null}>
          {children}
            <Toaster position="top-center" richColors closeButton />
               </Suspense>

              </ThemeProvider>

        {/* </Providers> */}
      </body>
    </html>
  );
}