import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
import { Suspense } from "react"
import { Analytics } from "@vercel/analytics/next"


const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
       <Suspense fallback={null}>{children}
        <Toaster />
       </Suspense>
        <Analytics />
      </body>
    </html>
  )
}
